version: 3
services:
  calibreweb:
    image: linuxserver/calibre-web:latest
    container_name: calibreweb
    restart: unless-stopped
    env_file:
      - stack.env
    network_mode: calibreweb-default
    labels:
      - appport=8083
    volumes:
      - /files/containers/calibreweb/config:/config
      - /files/containers/calibreweb/download:/download
      - /files/containers/calibreweb/books:/books
    ports:
      - 8083:8083
