version: '3.1'

services:
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8002:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=172.17.0.4
      - PMA_PORT=3306
      - PMA_USER=root
