version: "3"
services:
  privatebin:
    image: privatebin/nginx-fpm-alpine
    container_name: privatebin
    restart: unless-stopped
    volumes:
      - /files/containers/privatebin/data/:/data
      - /files/containers/privatebin/config/:/config
    ports:
      - 80004:80
