services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=rozul.com
      - VALIDATION=dns
      - EMAIL= apuente@hackarandas
      - DNSPLUGIN=cloudflare 
      - ONLY_SUBDOMAINS=false 
      - CERTPROVIDER= #optional
      - PROPAGATION= #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - /path/to/swag/config:/config
    ports:
      - 443:443
      # - 80:80 #optional
    restart: unless-stopped