---
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=113
      - PGID=120
      - TZ=US/Pacific
      - PIAUSER=x7406323
      - PIAPASS=peFQDJ83SG
      - PIAENDPOINT=Hungary
      - DOCKER_MODS=taisun/config-mods:pia
    volumes:
      - /files/containers/transmission/watch:/watch:rw
      - /files/containers/transmission/config:/config:rw
      - /files/containers/transmission/data:/downloads:rw
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
