version: '3.3'
services:
    transmission-openvpn:
        image: haugene/transmission-openvpn
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        volumes:
            - /files/containers/transmission/data:/data
            - /files/containers/transmission/config:/config
        env_file:
          - stack.env
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
