version: "3"
services:
  yourls:
    image: yourls:fpm-alpine
    container_name: yourls_YOURLS
    restart: unless-stopped
    volumes:
      - /files/containers/yourls/data/:/data
    ports:
      - 8003:80
